In [2]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4,5])
s=pd.Series(a)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4,5])
s=pd.Series(a,index=['first','second','third','fourth','fofth'])
print(s)

first     1
second    2
third     3
fourth    4
ftfth     5
dtype: int64

In [9]:
import pandas as pd
s=pd.Series(50,index=[0,1,2,3,4])
print(s)

0    50
1    50
2    50
3    50
4    50
dtype: int64

In [12]:
import pandas as pd
d={'name':"khush",'iplteam':"CSK",'runs':1200}
s=pd.Series(d)
print(s)

name       khush
iplteam      CSK
runs        1200
dtype: object

In [16]:
import pandas as pd
import numpy as np
s=pd.Series([1,2,3,4,5])
print("multiply all values by 2 ")
print(s*2)
print("multiply all values by 2 power ")
print(s**2)
print("to print all the values in a series that grrater than 2")
print(s[s>2])

multiply all values by 2
0     2
1     4
2     6
3     8
4    10
dtype: int64
multiply all values by 2 power
0     1
1     4
2     9
3    16
4    25
dtype: int64
to print all the values in a series that grrater than 2
2    3
3    4
4    5
dtype: int64

In [19]:
import pandas as pd
import numpy as np
s1=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
s2=pd.Series([10,20,30,40,50],index=['a','b','c','d','e'])
s3=pd.Series([4,13,43,4],index=['a','b','c','d'])
print("print bothe series sum of s1 and s2")
print(s1+s2)

print("print bothe series sum of s2 and s3")
print(s2+s3)

print("to add two s2 and s3 and filled non matching index with 0")
print(s2.add(s3,fill_value=0))

print bothe series sum of s1 and s2
a    11
b    22
c    33
d    44
e    55
dtype: int64
print bothe series sum of s2 and s3
a    14.0
b    33.0
c    73.0
d    44.0
e     NaN
dtype: float64
to add two s2 and s3 and filled non matching index with 0
a    14.0
b    33.0
c    73.0
d    44.0
e    50.0
dtype: float64

In [20]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
s=pd.Series(a)
print(s.head())
print(s.head(3))

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
dtype: int64

In [21]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
s=pd.Series(a)
print(s.tail())
print(s.tail(4))

5     6
6     7
7     8
8     9
9    10
dtype: int64
6     7
7     8
8     9
9    10
dtype: int64

In [22]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4,5])
s=pd.Series(a)
print(s)
print(s.loc[:2])
print(s.loc[3:4])
s.loc[2:3]

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
dtype: int64
3    4
4    5
dtype: int64

2    3
3    4
dtype: int64

In [23]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4,5])
s=pd.Series(a)
print(s)
print(s.iloc[:2])
print(s.iloc[3:4])
s.iloc[2:3]

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
dtype: int64
3    4
dtype: int64

2    3
dtype: int64

In [25]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4,5])
s=pd.Series(a)
print(s)
print(s[1])
print('\n')
print(s[3:4])
s[:3]

0    1
1    2
2    3
3    4
4    5
dtype: int64
2


3    4
dtype: int64

0    1
1    2
2    3
dtype: int64

In [26]:
import pandas as pd
import numpy as np
a=np.array(['a','b','c','d','e'])
s=pd.Series(a,index=['first','second','third','fourth','ftfth'])
print(s)
print("\nindexes in series are :: ")
print(s.index)

first     a
second    b
third     c
fourth    d
ftfth     e
dtype: object

indexes in series are ::
Index(['first', 'second', 'third', 'fourth', 'ftfth'], dtype='object')

In [27]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4,5])
s=pd.Series(a,index=['a','b','c','d','e'])
print(s)
print(s[1:5:2])
print(s[0:6:2])

a    1
b    2
c    3
d    4
e    5
dtype: int64
b    2
d    4
dtype: int64
a    1
c    3
e    5
dtype: int64

In [29]:
import pandas as pd
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [30]:
import pandas as pd
s=pd.Series(['a','b','c','d','e'])
df=pd.DataFrame(s)
print(df)

   0
0  a
1  b
2  c
3  d
4  e

import pandas as pd
name=pd.Series(['Hardik','Virat'])
team=pd.Series(['MI','RCB'])
dic={'name':name,'team':team}
df=pd.DataFrame(dic)
print(df)

In [31]:
import pandas as pd
name=pd.Series(['Hardik','Virat'])
team=pd.Series(['MI','RCB'])
dic={'name':name,'team':team}
df=pd.DataFrame(dic)
print(df)

     name team
0  Hardik   MI
1   Virat  RCB

In [32]:
import pandas as pd
l=[{"Name":'Sachin','SirName':'Bhardwaj'},
   {"Name":'Vinod','SirName':'Verma'},
   {"Name":'Rajesh','SirName':'MIshara'}]
df1=pd.DataFrame(l)
print(df1)

     Name   SirName
0  Sachin  Bhardwaj
1   Vinod     Verma
2  Rajesh   MIshara

import pandas as pd
l=[{"Name":'Sachin','SirName':'Bhardwaj'},
   {"Name":'Vinod','SirName':'Verma'}]
df1=pd.DataFrame(l)
print(df1)
for(row_index,row_value) in df1.ite

In [34]:
import pandas as pd
l=[{"Name":'Sachin','SirName':'Bhardwaj'},
   {"Name":'Vinod','SirName':'Verma'}]
df1=pd.DataFrame(l)
print(df1)
for(row_index,row_value) in df1.iterrows():
    print('\n Row index is :: ',row_index)
    print('Row value is ::')
    print(row_value)

     Name   SirName
0  Sachin  Bhardwaj
1   Vinod     Verma

 Row index is ::  0
Row value is ::
Name         Sachin
SirName    Bhardwaj
Name: 0, dtype: object

 Row index is ::  1
Row value is ::
Name       Vinod
SirName    Verma
Name: 1, dtype: object

In [42]:
import pandas as pd
empdata={'empid':[101,102,103,104,105,106],
         'ename':['khush','khushi','jiya','zankhana','vidhi','prinshi'],
         'doj':['12-01-2022','1-01-2022','2-08-2012','12-08-2002','2-05-2003','12-01-2022']
        }
df=pd.DataFrame(empdata)
print(df)

   empid     ename         doj
0    101     khush  12-01-2022
1    102    khushi   1-01-2022
2    103      jiya   2-08-2012
3    104  zankhana  12-08-2002
4    105     vidhi   2-05-2003
5    106   prinshi  12-01-2022

In [43]:
df.empid

0    101
1    102
2    103
3    104
4    105
5    106
Name: empid, dtype: int64

In [44]:
df[['empid','ename']]

   empid     ename
0    101     khush
1    102    khushi
2    103      jiya
3    104  zankhana
4    105     vidhi
5    106   prinshi

In [46]:
import pandas as pd
s=pd.Series([1,2,3,4])
df=pd.DataFrame(s)
df.columns=['list1']
df['list2']=20
df['list3']=df['list2']+df['list1']
print(df)

   list1  list2  list3
0      1     20     21
1      2     20     22
2      3     20     23
3      4     20     24

In [48]:
import pandas as pd
s=pd.Series([1,2,3,4])
df=pd.DataFrame(s)
df.columns=['list1']
df['list2']=40
df1=df.drop('list2',axis=1)
df2=df.drop(index=[2,3],axis=0)
print(df)
print("Aftre deletion :: ")
print(df1)
print("Aftre row deletion :: ")
print(df2)

   list1  list2
0      1     40
1      2     40
2      3     40
3      4     40
Aftre deletion ::
   list1
0      1
1      2
2      3
3      4
Aftre row deletion ::
   list1  list2
0      1     40
1      2     40

In [51]:
import pandas as pd
runs={'TCS':{'qtr1':2500,'qtr2':2000,'qtr3':3000,'qtr4':2000},
      'WIPRO':{'qtr1':2500,'qtr2':2000,'qtr3':3000,'qtr4':2000},
      'L&T':{'qtr1':2500,'qtr2':2000,'qtr3':3000,'qtr4':2000}}

df=pd.DataFrame(runs)
print(df)
print(df.loc['qtr3':])
print(df.loc['qtr1':'qtr3',:])

       TCS  WIPRO   L&T
qtr1  2500   2500  2500
qtr2  2000   2000  2000
qtr3  3000   3000  3000
qtr4  2000   2000  2000
       TCS  WIPRO   L&T
qtr3  3000   3000  3000
qtr4  2000   2000  2000
       TCS  WIPRO   L&T
qtr1  2500   2500  2500
qtr2  2000   2000  2000
qtr3  3000   3000  3000

In [52]:
import pandas as pd
runs={'TCS':{'qtr1':2500,'qtr2':2000,'qtr3':3000,'qtr4':2000},
      'WIPRO':{'qtr1':2500,'qtr2':2000,'qtr3':3000,'qtr4':2000},
      'L&T':{'qtr1':2500,'qtr2':2000,'qtr3':3000,'qtr4':2000}}

df=pd.DataFrame(runs)
print(df)
print(df.loc[:,'TCS'])
print(df.loc[:,'TCS':"WIPRO"])

       TCS  WIPRO   L&T
qtr1  2500   2500  2500
qtr2  2000   2000  2000
qtr3  3000   3000  3000
qtr4  2000   2000  2000
qtr1    2500
qtr2    2000
qtr3    3000
qtr4    2000
Name: TCS, dtype: int64
       TCS  WIPRO
qtr1  2500   2500
qtr2  2000   2000
qtr3  3000   3000
qtr4  2000   2000

In [53]:
import pandas as pd
empdata={'empid':[101,102,103,104,105,106],
         'ename':['khush','khushi','jiya','zankhana','vidhi','prinshi'],
         'doj':['12-01-2022','1-01-2022','2-08-2012','12-08-2002','2-05-2003','12-01-2022']
        }
df=pd.DataFrame(empdata)
print(df)
print(df.loc[0])
df.loc[0:2]

   empid     ename         doj
0    101     khush  12-01-2022
1    102    khushi   1-01-2022
2    103      jiya   2-08-2012
3    104  zankhana  12-08-2002
4    105     vidhi   2-05-2003
5    106   prinshi  12-01-2022
empid           101
ename         khush
doj      12-01-2022
Name: 0, dtype: object

   empid   ename         doj
0    101   khush  12-01-2022
1    102  khushi   1-01-2022
2    103    jiya   2-08-2012

In [54]:
import pandas as pd
runs={'TCS':{'qtr1':2500,'qtr2':2000,'qtr3':3000,'qtr4':2000},
      'WIPRO':{'qtr1':2500,'qtr2':2000,'qtr3':3000,'qtr4':2000},
      'L&T':{'qtr1':2500,'qtr2':2000,'qtr3':3000,'qtr4':2000}}

df=pd.DataFrame(runs)
print(df)
print(df.iloc[0:2,1:2])
print(df.iloc[:,0:2])

       TCS  WIPRO   L&T
qtr1  2500   2500  2500
qtr2  2000   2000  2000
qtr3  3000   3000  3000
qtr4  2000   2000  2000
      WIPRO
qtr1   2500
qtr2   2000
       TCS  WIPRO
qtr1  2500   2500
qtr2  2000   2000
qtr3  3000   3000
qtr4  2000   2000

In [55]:
import pandas as pd
empdata={'empid':[101,102,103,104,105,106],
         'ename':['khush','khushi','jiya','zankhana','vidhi','prinshi'],
         'doj':['12-01-2022','1-01-2022','2-08-2012','12-08-2002','2-05-2003','12-01-2022']
        }
df=pd.DataFrame(empdata)
print(df)
print(df.head())
print(df.tail())

   empid     ename         doj
0    101     khush  12-01-2022
1    102    khushi   1-01-2022
2    103      jiya   2-08-2012
3    104  zankhana  12-08-2002
4    105     vidhi   2-05-2003
5    106   prinshi  12-01-2022
   empid     ename         doj
0    101     khush  12-01-2022
1    102    khushi   1-01-2022
2    103      jiya   2-08-2012
3    104  zankhana  12-08-2002
4    105     vidhi   2-05-2003
   empid     ename         doj
1    102    khushi   1-01-2022
2    103      jiya   2-08-2012
3    104  zankhana  12-08-2002
4    105     vidhi   2-05-2003
5    106   prinshi  12-01-2022

In [56]:
import pandas as pd
empdata={'empid':[101,102,103,104,105,106],
         'ename':['khush','khushi','jiya','zankhana','vidhi','prinshi'],
         'doj':['12-01-2022','1-01-2022','2-08-2012','12-08-2002','2-05-2003','12-01-2022']
        }
df=pd.DataFrame(empdata)
print(df)
print(df.head(2))
print(df.tail(2))
print(df[2:5])

   empid     ename         doj
0    101     khush  12-01-2022
1    102    khushi   1-01-2022
2    103      jiya   2-08-2012
3    104  zankhana  12-08-2002
4    105     vidhi   2-05-2003
5    106   prinshi  12-01-2022
   empid   ename         doj
0    101   khush  12-01-2022
1    102  khushi   1-01-2022
   empid    ename         doj
4    105    vidhi   2-05-2003
5    106  prinshi  12-01-2022
   empid     ename         doj
2    103      jiya   2-08-2012
3    104  zankhana  12-08-2002
4    105     vidhi   2-05-2003

In [58]:
import pandas as pd

dic1 = {'id': ['1', '2', '3', '4', '5'], 'Value1': ['A', 'C', 'E', 'G', 'I'],
       'Value2':['B','D','F','H','J']}
dic2 = {'id': ['2', '3', '6', '7', '8'], 'Value1': ['K', 'M', 'O', 'Q', 'S'],
        'Value2': ['L', 'N', 'P', 'R', 'T']}

df1 = pd.DataFrame(dic1)
df2 = pd.DataFrame(dic2)

df3 = pd.merge(df1, df2, on='id', how='outer')

print(df3)

  id Value1_x Value2_x Value1_y Value2_y
0  1        A        B      NaN      NaN
1  2        C        D        K        L
2  3        E        F        M        N
3  4        G        H      NaN      NaN
4  5        I        J      NaN      NaN
5  6      NaN      NaN        O        P
6  7      NaN      NaN        Q        R
7  8      NaN      NaN        S        T

In [60]:
import pandas as pd

# Creating dictionaries
dic1 = {'id': ['1', '2', '3', '4', '5'], 'Value1': ['A', 'C', 'E', 'G', 'I']}
dic2 = {'id': ['2', '3', '6', '7', '8'], 'Value1': ['K', 'M', 'O', 'Q', 'S'], 'Value2': ['L', 'N', 'P', 'R', 'T']}

# Creating DataFrames
df1 = pd.DataFrame(dic1)
df2 = pd.DataFrame(dic2)

# Corrected merge statement
df3 = pd.merge(df1, df2, on='id', how='outer', suffixes=('_left', '_right'))

print(df3)

  id Value1_left Value1_right Value2
0  1           A          NaN    NaN
1  2           C            K      L
2  3           E            M      N
3  4           G          NaN    NaN
4  5           I          NaN    NaN
5  6         NaN            O      P
6  7         NaN            Q      R
7  8         NaN            S      T

In [61]:
import pandas as pd

dic1 = {'id': ['1', '2', '3', '4', '5'], 'Value1': ['A', 'C', 'E', 'G', 'I'],
       'Value2':['B','D','F','H','J']}
dic2 = {'id': ['2', '3', '6', '7', '8'], 'Value1': ['K', 'M', 'O', 'Q', 'S'],
        'Value2': ['L', 'N', 'P', 'R', 'T']}

df1 = pd.DataFrame(dic1)
df2 = pd.DataFrame(dic2)

df3 = pd.merge(df1, df2, on='id', how='inner')

print(df3)

  id Value1_x Value2_x Value1_y Value2_y
0  2        C        D        K        L
1  3        E        F        M        N